CREATE TABLE BRAND (
	ID   INT         PRIMARY KEY,
	NAME VARCHAR(50) UNIQUE NOT NULL CHECK (NAME ~ '\S')
);

CREATE TABLE CATEGORY (
	ID   INT         PRIMARY KEY,
	NAME VARCHAR(50) UNIQUE NOT NULL CHECK (NAME ~ '\S')
);

CREATE TABLE PRODUCT (
	ID          VARCHAR(20)    PRIMARY KEY,
	RETAILER_ID VARCHAR(20)    NOT NULL,
	SKU         VARCHAR(12)    NOT NULL,
	NAME        VARCHAR(100)   NOT NULL CHECK (NAME ~ '\S'),
	DESCRIPTION VARCHAR(250)   NOT NULL CHECK (DESCRIPTION ~ '\S'),
	PRICE       NUMERIC(12, 2) NOT NULL CHECK (PRICE > 0),
	INVENTORY   INT            NOT NULL CHECK (INVENTORY > 0),
	BRAND_ID    INT            REFERENCES BRAND(ID),
	CREATED_AT  TIMESTAMP      NOT NULL,
	UPDATED_AT  TIMESTAMP      NOT NULL CHECK (UPDATED_AT >= CREATED_AT)
);

CREATE TABLE PRODUCT_CATEGORY (
	ID          INT         PRIMARY KEY,
	PRODUCT_ID  VARCHAR(20) REFERENCES PRODUCT(ID),
	CATEGORY_ID INT         REFERENCES CATEGORY(ID)
);

